title = "Jinwoo Park Blog"
logo = "img/LambdaEE.png"
copyright = "Jinwoo Park, CC-BY-SA"
languageName = "日本語 (JA)"
languageCode = "ja-JP"
weight = 2

[author]
name = "Jinwoo Park"
image = "img/profile.jpeg"
headline = "Rust + Linux + Embedded + Electronics"
bio = "Rustバックエンドエンジニアとして働いており、以前は組込みシステムエンジニアとして勤務していました。"
links = [
  { github = "https://github.com/pmnxis" },
]

[params]
  displayName = "JA"
  isoCode = "ja"